### ISSUE TITLE
Dedicated invoice view when clicking on an invoice

### ISSUE THREAD

**Issue by CBMR** [BloomTech-Labs/labspt2-auto-invoicer#119]
Possibly add two additional buttons: 

_Add Payment_  and _Edit_

**Add Payment** just updates the `amountPaid` field and the BE logic toggles the `paid` boolean, if `amountPaid  >= balance`

**Edit** takes the user to the Edit view, so they could edit anything else

**Comment by Dewayne87** [comment]
done
